loopback_users.guest = false

total_memory_available_override_value = 4294967296

listeners.tcp.default = 5672

management.tcp.port = 15672

load_definitions = /etc/rabbitmq/definitions.json

default_user=rabbit
default_pass=NKZSQw4cVIwPT+Zh0gwJKL7ghm0v/kNe4dCPRy8kQDcl/16p
