server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: cs-m5
  profiles:
    active: ${ACTIVE_PROFILE:dev}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5448}/${DB_NAME:cs-m5}?stringtype=unspecified
    username: ${DB_USER:csm5Admin}
    password: ${DB_PASSWORD:81238438192@3891}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        event:
          merge:
            entity_copy_observer: allow

  mongodb:
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT_PORT:27037}
    username: ${MONGO_USERNAME:mongo-user}
    password: ${MONGO_PASSWORD:adj2ir9w1k3herw9f228}
    database: ${MONGO_DB:csm5}

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5678}
    username: ${RABBIT_USER:rabbit}
    password: ${RABBIT_PASSWORD:ouw802jfsoaqsas}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6399}
      client-type: jedis

management:
  server:
    port: ${MANAGEMENT_PORT:8090}
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info
    enabled-by-default: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
    info:
      enabled: true